[versions]
agp = "8.5.0"
credentials = "1.2.2"
dotsindicator = "5.0"
datastorePreferencesCore = "1.1.1"
dotsindicatorVersion = "5.0"
googleid = "1.1.1"
credentialsPlayServicesAuth = "1.2.2"
hiltNavigationFragment = "1.2.0"
kotlin = "1.9.21"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
coroutines = "1.7.3"
material = "1.12.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
navigation = "2.7.7"
datastore = "1.1.1"
lifecycle-runtime-ktx = "2.8.3"
lifecycle-extensions = "2.2.0"
pagingRuntimeKtx = "3.3.1"
workRuntimeKtx = "2.9.0"

# BootPay
bootPay = "4.4.1"

# Firebase
firebaseBom = "33.1.2"
fcm = "24.0.0"
google-services = "4.3.15"

# Maps
playServicesLocation = "21.3.0"
navermaps = "3.18.0"

# Logging
timber = "5.0.1"

# Media
glide = "4.15.0"

# DI
hilt = "2.51.1"
hiltCompiler = "1.2.0"
hiltWork = "1.2.0"

# Network & Serialization
kotlinx-serialization = "1.6.2"
okhttp = "4.12.0"
retrofit = "2.11.0"

# Permission
ted-permission = "3.3.0"
googleidVersion = "1.1.1"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastorePreferencesCore" }
androidx-hilt-navigation-fragment = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "hiltNavigationFragment" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltWork" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicatorVersion" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle-extensions" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

# BootPay
bootpay = {group="io.github.bootpay", name="android", version.ref ="bootPay"}

# Firebase
firebase-cloud-messaging = { group = "com.google.firebase", name = "firebase-messaging-ktx", version.ref = "fcm" }

# Maps
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
naver-maps = { group = "com.naver.maps", name = "map-sdk", version.ref = "navermaps" }

# Media
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

# Logging
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Permission
ted-permission-normal = { group = "io.github.ParkSangGwon", name = "tedpermission-normal", version.ref = "ted-permission" }
ted-permission-coroutine = { group = "io.github.ParkSangGwon", name = "tedpermission-coroutine", version.ref = "ted-permission" }

# DI
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }
# Network & Serialization
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttp" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-converter-kotlinxSerialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
google-googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleidVersion" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
hilt-gradle-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
navigation-safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
